import React from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

const s = {
  hero: { textAlign: 'center', padding: '80px 24px', maxWidth: 600, margin: '0 auto' },
  h1: { fontSize: 40, fontWeight: 800, color: '#1e1b4b', marginBottom: 16 },
  sub: { fontSize: 18, color: '#6b7280', marginBottom: 40, lineHeight: 1.6 },
  btnGroup: { display: 'flex', gap: 12, justifyContent: 'center', flexWrap: 'wrap' },
  primary: { background: '#4f46e5', color: '#fff', padding: '12px 28px', fontSize: 16 },
  secondary: { background: '#e5e7eb', color: '#374151', padding: '12px 28px', fontSize: 16 },
  features: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 24, padding: '40px 24px', maxWidth: 900, margin: '0 auto' },
  card: { background: '#fff', borderRadius: 12, padding: 24, boxShadow: '0 1px 4px rgba(0,0,0,0.08)' },
  cardTitle: { fontWeight: 700, marginBottom: 8, color: '#1e1b4b' },
};

const features = [
  { title: 'Post Activities', desc: 'Share what you want to do and when — hiking, food tours, nightlife, and more.' },
  { title: 'Smart Matching', desc: 'Get matched with compatible travelers based on interests, timing, and vibe.' },
  { title: 'AI Itinerary', desc: 'Receive a personalized day plan generated by AI for your matched pair.' },
  { title: 'Feedback Loop', desc: 'Rate your experience to help the matching algorithm improve over time.' },
];

export default function HomePage() {
  const { user } = useAuth();
  return (
    <div>
      <div style={s.hero}>
        <h1 style={s.h1}>Meet Your Perfect Travel Companion</h1>
        <p style={s.sub}>Find solo travelers doing exactly what you want to do, in the same city, on the same day.</p>
        <div style={s.btnGroup}>
          {user ? (
            <Link to="/activities"><button style={s.primary}>Browse Activities</button></Link>
          ) : (
            <>
              <Link to="/register"><button style={s.primary}>Get Started</button></Link>
              <Link to="/login"><button style={s.secondary}>Sign In</button></Link>
            </>
          )}
        </div>
      </div>
      <div style={s.features}>
        {features.map((f) => (
          <div key={f.title} style={s.card}>
            <div style={s.cardTitle}>{f.title}</div>
            <div style={{ color: '#6b7280', fontSize: 14, lineHeight: 1.6 }}>{f.desc}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
